use_frameworks!
use_modular_headers!

target 'NearbyUserdetails_Example' do
  pod 'NearbyUserdetails', :path => '../'

  target 'NearbyUserdetails_Tests' do
    inherit! :search_paths

    
  end
end
